---
layout: page
title: About
permalink: /about/
---

# Why I write

I want to share. And I believe that writing is a process where scrambled thoughts can be converted into shareable information.

In math, processes are called functions. In writing, my thoughts are the inputs, writing is the function, and this post is my output. In statistics, the truth is unattainable, only estimable. Writing is the function that uses my thoughts to estimate truth. And bias is the distance from the truth. In reading my writing, there are two biases at play for you: my writing's distance from the truth and your distance from understanding my writing. I hope by writing often I can reduce both sources of bias. Better writing means better sharing, and sharing truth helps us both.

My hope is that those who read this blog will take away from it a portion of what I've gained from others. It's likely that this blog is more valueable for me than it is for you, but I hope that what I've learned can help. If it does, please share.

# About me

I received a BS and MS in Statistics from Brigham Young University. During my programs, I first learned to code in R and SAS and have since been learning Stata, Visual Basic for Applications (VBA), Python, [vi], and [RShiny]. I currently work as a consultant/data scientist for [Bates White], where I milk[^1], munge, merge, and model data of all types.

Previously, I've spent two years as a missionary for The Church of Jesus Christ of Latter-day Saints in and around Tegucigalpa, Honduras. In my spare time, I enjoy writing songs on the piano or guitar and volunteering at my church. If I had snow nearby, I would ski it. But living in Washington, DC has its perks, such as being able to ride home past the Washington monument every day. My wife Veronica and I enjoy long walks through the park, and if we had a beach nearby, we'd probably enjoy long walks there too.

[^1]: And by milk I mean webscrape. (I needed an "m" for the alliteration.)
[Bates White]:http://www.bateswhite.com/
[vi]:https://en.wikipedia.org/wiki/Vi
[RShiny]:http://shiny.rstudio.com/
